version: "3.8"
services:
  lambda:
    build: .
    depends_on:
      - mysql
      - localstack
    environment:
      DB_HOST: mysql
      DB_DATABASE: app_db
      DB_USERNAME: app_user
      DB_PASSWORD: app_password
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-1
    volumes:
      - .:/app
      - /app/__pycache__

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      DB_PASSWORD: app_password
    ports:
      - "3307:3306" # ポート番号を変更してバッティング回避

  localstack:
    image: localstack/localstack:3.0
    environment:
      - SERVICES=sqs,lambda
      - DEBUG=1
    ports:
      - "4567:4566" # ポート番号を変更
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mysql_data:
