AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900 # スクレイピング処理のため15分に設定
    MemorySize: 512 # メモリサイズを512MBに設定
    Runtime: python3.13
    Tracing: Active
    Environment:
      Variables:
        PYTHONPATH: /var/task:/var/task/scrapers:/var/task/database
        SAVE_TO_DB: "true"
        LOG_LEVEL: "INFO"
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  LoanpediaScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: loanpedia_scraper/
      Handler: app.lambda_handler
      Description: 全金融機関のローン情報スクレイピング統合実行
      Architectures:
        - x86_64
      Events:
        MonthlySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(30 days) # 月次実行（30日ごと）
            Name: LoanpediaScraperMonthlySchedule
            Description: ローン情報スクレイピングの月次実行スケジュール
            Enabled: true

  # 青森みちのく銀行
  AomorimichinokuBankScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: loanpedia_scraper/
      Handler: src.handlers.aomori_mitinoku_bank.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 900
      Events:
        MonthlySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(30 days)
            Name: AomorimichinokuBankMonthlySchedule
            Description: 青森みちのく銀行の月次スクレイピング
            Enabled: true

  # 青い森信用金庫
  AoimoriShinkinScraperFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.13
    Properties:
      CodeUri: loanpedia_scraper/
      Handler: src.handlers.aoimori_shinkin.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 900
      Environment:
        Variables:
          PYTHONPATH: /var/task:/var/task/src
      Events:
        MonthlySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(30 days)
            Name: AoimoriShinkinMonthlySchedule
            Description: 青い森信用金庫の月次スクレイピング
            Enabled: true

  # 東奥信用金庫
  TououshinkinScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: loanpedia_scraper/
      Handler: src.handlers.touou_shinkin.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 900
      Events:
        MonthlySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(30 days)
            Name: TououshinkinMonthlySchedule
            Description: 東奥信用金庫の月次スクレイピング
            Enabled: true

  # 青森県信用組合
  AomorikenshinyoukumiaiScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: loanpedia_scraper/
      Handler: src.handlers.aomoriken_shinyoukumiai.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 900
      Events:
        MonthlySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(30 days)
            Name: AomorikenshinyoukumiaiMonthlySchedule
            Description: 青森県信用組合の月次スクレイピング
            Enabled: true

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
Outputs:
  LoanpediaScraperFunction:
    Description: メインスクレイピング Lambda Function ARN
    Value: !GetAtt LoanpediaScraperFunction.Arn
  AoimoriShinkinScraperFunction:
    Description: 青い森信用金庫スクレイピング Lambda Function ARN
    Value: !GetAtt AoimoriShinkinScraperFunction.Arn
  AomorimichinokuBankScraperFunction:
    Description: 青森みちのく銀行スクレイピング Lambda Function ARN
    Value: !GetAtt AomorimichinokuBankScraperFunction.Arn
  TououshinkinScraperFunction:
    Description: 東奥信用金庫スクレイピング Lambda Function ARN
    Value: !GetAtt TououshinkinScraperFunction.Arn
  AomorikenshinyoukumiaiScraperFunction:
    Description: 青森県信用組合スクレイピング Lambda Function ARN
    Value: !GetAtt AomorikenshinyoukumiaiScraperFunction.Arn
